database設計
okamin07/furima-877877 pull request #1
Opened 2021-01-17 12:00 UTC by okamin07

# WHAT
アプリで使用するデータベースを設計した。
imageは最初はactivestorageを使うのかな？と思ったのでカラムは用意していない。
クレジットカードの情報もあとでpay.jpでやるんかなと思ったので一旦省略した。

# WHY
ユーザー、商品の情報を保存し管理するため。

2021-01-17 12:23 UTC, okamin07 commented
# 待て
## ①明らかにカラムが足りてない
・名前（氏名、漢字/かな）
・建物名

## ②orderおかしくない？
・商品がわからんよね
・住所はユーザーと紐づいてるからいらん？

## ③購入の判定（売り切れたかどうか）の判定できんくない？
・なんかidつけて判別するみたいな話を聞いたぞ

2021-01-17 12:32 UTC, okamin07 commented
『既読機能をつけよう』的な記事をみて
「なるほど、売り上げの判定もこれ使ってboolean（真偽値）でやったらいいんじゃね？」
と思ったのだが、、、

2021-01-17 13:20 UTC, sakiytn requested changes

2021-01-17 13:20 UTC, sakiytn commented on README.md
> +|password|string|null: false|
8行目のpasswordの記述は、デフォルトのencrypted_passwordと重複しているため削除しましょう！
（確認用PWはDBに保存されないからカラムは1つでOK！）

2021-01-17 14:18 UTC, sakiytn approved these changes
DB設計お疲れさま、そしてPRありがとう！
全体的に丁寧に設計している印象でとっても嬉しかったです。

細かいところも含めていくるかコメントしているので、修正をお願いします。
不明点があればいつでも質問してね〜

2021-01-17 14:18 UTC, sakiytn commented on README.md
> +- has_one:address
```
has_one:address
```
ここに関して、Furimaの必須機能ではユーザーに対して住所のアソシエーションは組まなくてもいい仕様になっていたはず⋯！（一人のユーザーが複数の住所で購入することができる、という意味）
追加実装としてユーザーに対してカードと住所を紐付ける機能を入れるのであれば必要ですが、個人的には必須機能においては不要かなと思います。

2021-01-17 14:18 UTC, sakiytn commented on README.md
> +|shiping_date|date|null: false|
```
|category|string|null: false|
|status|string|null: false|
|delivery_fee|string|null: false|
|shiping_address|string|null: false|
|shiping_date|date|null: false|
```
こちらの29-33行目はActive Hashからデータを選択させる項目のため、カラム名は「モデル名_id」に統一しましょう。
また、それに合わせてカラムの型もidで管理するためにintegerに揃えましょう！

2021-01-17 14:18 UTC, sakiytn commented on README.md
> +|price|string|null: false|
```
|price|string|null: false|
```
priceの型は半角数字での入力が必須のためstringではなさそうですね。
どの型が適切かもう一度考えてみましょう！

2021-01-17 14:18 UTC, sakiytn commented on README.md
> +|user|reference|null: false, foreign_key: true|
```
|user|reference|null: false, foreign_key: true|
|user|reference|null: false, foreign_key: true|
```
表記が重複してしまっているので、1行分を削除しましょう！
（お疲れの様子が見えるのでここで温かい飲み物を飲んで一息つこう）

2021-01-17 14:18 UTC, sakiytn commented on README.md
> +|sold|boolean||
```
|sold|boolean||
```
確かにここは悩むよね、、結論、このカラムは不要です！
理由としては「購入済みであれば購入履歴を管理しているOrderモデルにデータが保存されるから」です。
（booleanは調べてみないとなかなか思いつかない発想だと思う、ナイス仮説！）

2021-01-17 14:18 UTC, sakiytn commented on README.md
> +- belongs_to:user
```
has_many:items 
```
購入履歴に紐づく商品は1点のみです。
アソシエーションを修正しましょう！
また、購入履歴と住所情報を紐づける必要があるため、Addressモデルとのアソシエーションも組んであげましょう〜（ここは疑問に思うところだと思うのでいつでも質問まってます！）

2021-01-17 14:18 UTC, sakiytn commented on README.md
> +- belongs_to:user
難しいAddressモデルの設計も、全体的によくできてます！
以下の3点だけ、修正をお願いします。

1. 都道府県カラムを修正しましょう
```
|prefecture|string|null: false|
```
　こちらはitemsテーブルでも使用している都道府県を扱うActive Hashを使い回したいので、
　先述した通りカラム名を「モデル名_id」に、型を「integer」に修正しましょう！


2. ordersテーブルの外部キーをつくりましょう
”購入履歴に紐づいた住所”として管理をしたいため、ordersテーブルの外部キーを加えましょう！


3. アソシエーションを見直しましょう
2.で先述している通りです。
AddressモデルをOrderモデルへ紐付けるためのアソシエーションを組みましょう！



P.S) postcodeとphone_numberをstringにできているところが素晴らしいです！！
　　なぜintegerでは設計しないのか、ぜひアウトプットしてみてね〜

2021-01-17 14:19 UTC, sakiytn approved these changes

2021-01-17 14:19 UTC, sakiytn commented on README.md
> +|encrypted_password|string|null: false|
```
|mail|string|null: false|
```
こちらのカラム名はdeviseのデフォルトに合わせて「email」としましょう。（細かくてごめんね）

```
|password|string|null: false|
```
また、こちらのカラムはデフォルトのencrypted_passwordと重複しているため削除しましょう！
（確認用PWはDBに保存されないためデフォルトのencrypted_passwordのみでOK）

2021-01-18 01:00 UTC, okamin07 commented on README.md
> +- has_one:address
そっか！Amazonとかでも配送先複数設定出来るもんね！

2021-01-18 01:04 UTC, okamin07 commented on README.md
> +|shiping_date|date|null: false|
なるほど！
` {id: 1, name: '北海道'},`
のidだけが保存されるのか

2021-01-18 01:08 UTC, okamin07 commented on README.md
> +|price|string|null: false|
integerにしてみました！！

2021-01-18 01:08 UTC, okamin07 commented on README.md
> +|user|reference|null: false, foreign_key: true|
コーヒー飲んでます！w

2021-01-18 01:16 UTC, okamin07 commented on README.md
> +|sold|boolean||
カリキュラム先回りして読みました！
item.order(かはわからんけど)で、「商品に紐づくorderがある/ない」で判別するのね！

2021-01-18 01:26 UTC, okamin07 commented on README.md
> +- belongs_to:user
そっかフリマで出品されてる商品は1点限りか（複数買えるイメージでやってた笑）
「1つの商品の発送先は1箇所」だと思ったので `has_one:address` にした！

2021-01-18 02:08 UTC, okamin07 commented on README.md
> +- belongs_to:user
## ①修正
修正！

## ②ちょっと疑問
ここちょっと悩んだ！
なんでaddressテーブルで購入履歴を管理するんだろう？？

以下仮説！
```
|user|item|address|
|誰が|何を|どこに|
```
の方が直感的やな、、、
って思ったけど、それだと引っ張ってくるデータが多すぎる？のでaddressテーブルで管理する。
- 「address_id:1」で「post_code」から「phone_number」まで引っ張るのは重い？
- 「addressテーブルでorderを参照」にしたら、引っ張るデータは「user」「item」だけでいい

## ③修正
参照元であるorderが親テーブルだと思ったので `belongs_to:order` で！

## アウトプット：なぜintegerではないのか
ぶっちゃけ何も考えずにやった！笑
けど、調べたアンド考えた結果、以下が理由！
・電話番号は「0」から始まる→0で始まる整数はないので、integerだと正しく認識されない
・郵便番号はハイフンも登録するから！

2021-01-18 02:09 UTC, okamin07 commented on README.md
> +|encrypted_password|string|null: false|
どちらも修正！

2021-01-18 02:15 UTC, sakiytn commented on README.md
> +- has_one:address
イェス！
必須機能の仕様を深掘っていくと「住所選択できたらいいのにな〜」とか+αの実装を考えたくなるよね笑

2021-01-18 02:18 UTC, sakiytn commented on README.md
> +|user|reference|null: false, foreign_key: true|
推しが淹れてくれたコーヒー⋯いいな⋯

2021-01-18 02:18 UTC, sakiytn commented on README.md
> +|shiping_date|date|null: false|
そうそう、その通り！
「Active Hashが持っているデータからidをとってくる」ってイメージだね。

2021-01-18 02:18 UTC, sakiytn commented on README.md
> +|user|reference|null: false, foreign_key: true|
推しが淹れてくれたコーヒー⋯いいな⋯

2021-01-18 02:19 UTC, sakiytn commented on README.md
> +|sold|boolean||
>item.order(かはわからんけど)で、「商品に紐づくorderがある/ない」で判別するのね！

完璧です！Orderモデルを設計している意図はそういうことだね！

2021-01-18 02:29 UTC, sakiytn commented on README.md
> +- belongs_to:user
ここも完璧っす！さすが！

# ②の疑問について
>「addressテーブルでorderを参照」にしたら、引っ張るデータは「user」「item」だけでいい

この仮説、バッチグーです！
あとはカリキュラムの意図として「購入履歴と住所情報をFormオブジェクトを使って一括登録させたい」という狙いがあるので、FurimaではOrderとAddressを紐付けているよ〜

# アウトプットありがと
ナイス検索&ナイスアウトプット👏！
記述してくれている通りで、ここはinteger型にしてしまう人が多いところです。
「0は整数ではない」という数学の知識と、「ハイフンがマスト」という実装条件を読み解く緻密さが必要だから特に難しいよね、、

2021-01-18 02:31 UTC, sakiytn approved these changes
addressesテーブルの修正が1点だけ漏れていたのでそこだけお願いします！
あとは完璧です〜！

2021-01-18 02:31 UTC, sakiytn commented on README.md
> +|prefecture|string|null: false|
```
|prefecture|string|null: false|
```
最後にここだけ修正が漏れていたのでお願いします！
itemsテーブルで設計している都道府県のカラムと同じように、Active Hash仕様で設計してあげよう！

2021-01-18 02:40 UTC, sakiytn commented on README.md
> +|prefecture|string|null: false|
あ、多分postdodeをidとintegerにしちゃってるみたいだね。
postcodeは元の「idなし・string」でOK！
都道府県のカラム名はitemsテーブルと揃えた方がいいと思うので「shiping_address_id」になるかな？

2021-01-18 03:23 UTC, okamin07 commented on README.md
> +|prefecture|string|null: false|
あざまる！！
post_codeは無思考だったw
>都道府県のカラム名はitemsテーブルと揃えた方がいいと思うので「shiping_address_id」になるかな？

紐づいてるのにカラム名違ったら「あれ、違うデータなの？？」ってなりそう！（俺はなる）

2021-01-18 04:04 UTC, sakiytn commented
LGTMです！！！
お疲れ様でしたーーーー！

2021-01-18 05:26 UTC, merged