商品出品機能
okamin07/furima-877877 pull request #5
Opened 2021-01-28 05:28 UTC by okamin07

# WHY
出品者（管理者）が1人しかいないECサイトとは違い、
フリーマーケットは "誰でも出品できる" 必要があるため。
新規登録/ログインしていれば**出品ページ**から商品を登録できるようにした。

# WHAT
商品出品機能を実装した

## 挙動
①ログイン状態のユーザーは、商品出品ページへ遷移できる動画

②金額が入力されると同時に、販売手数料と販売利益が表示される動画

③正しく情報を記入すると、商品を出品できる動画

④入力に問題のある状態では商品は出品できず、エラーメッセージが出力される動画

⑤ログアウト状態のユーザーは、商品出品ページへ遷移しようとすると、ログインページへ遷移する動画
⑥テスト結果の画像

2021-01-31 06:41 UTC, sakiytn requested changes
遅くなってしまって大変申し訳ない⋯！
全体的にとてもよくできています◎
主にバリデーションの記述についていくつか指摘しているので、修正をお願いします！

2021-01-31 06:41 UTC, sakiytn commented on app/javascript/item_price.js
> +    addProfitlDom.innerHTML = `${inputValue - tax}`
```
addTaxDom.innerHTML = `${tax}`
addProfitlDom.innerHTML = `${inputValue - tax}`
```
現状、価格を入力すると販売手数料と販売利益に小数点以下の数字が表示されてしまっています。
計算値の小数点を丸める(整数で表示させる)メソッドがJSにあるので、検索して実装に取り入れてみましょう！

2021-01-31 06:41 UTC, sakiytn commented on app/models/address.rb
> +  belongs_to :prefecture
```
extend ActiveHash::Associations::ActiveRecordExtensions
belongs_to :prefecture
```
Addressモデルの情報はビューへ渡さないため、こちらのActive Hashへのアソシエーションは不要です。
2,3行目を削除しましょう！

2021-01-31 06:41 UTC, sakiytn commented on app/models/item.rb
> +  has_one_attached :image
```
has_many:items 
has_many:orders 
```
こちらの2行目のアソシエーションですが、「商品が商品を複数持っている」ということになっているため、適切なモデルへのアソシエーションに修正しましょう！

また3行目のアソシエーションに関してですが、Furimaでは「1つの商品に対して購入履歴は1つ」という仕様となっています。こちらも仕様に沿ったアソシエーションを考えて修正をお願いします🙏！

2021-01-31 06:41 UTC, sakiytn commented on app/models/item.rb
> +  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300,less_than_or_equal_to:9999999},format: {with: /\A[0-9]+\z/}
```
  validates :image,:name,:details,:category_id,:status_id,:delivery_fee_id,:shiping_address_id,:shiping_date_id,:price,:user_id, presence: true 
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300,less_than_or_equal_to:9999999},format: {with: /\A[0-9]+\z/}
```
カラムが多くあるモデルのバリデーションの記述って難しいよね⋯！
結論、バリデーションはカラムごとに1行ずつ分けて記述してください！
（ユーザー管理機能で実装したuser.rbの記述を是非参考に◎）

また、7行目の価格についてのバリデーションについて見直しをお願いします！
現状として、以下4つのバリデーションをpriceに対してかけているようですね。
 - presence: true
 - numericality: {only_integer: true}
 - numericality: {(価格範囲のバリデーション)}
 - format: {with: /\A[0-9]+\z/}
 
一つのカラムに対し複数のバリデーションを加える際も、先述した通りバリデーションごとに改行して記述しましょう！具体的な記述方法については下記カリキュラムを参考にしてみてください。

**最終課題補足カリキュラム「〜1つのフォームから複数のテーブルに情報を保存するアプリを作成しよう〜」**
https://master.tech-camp.in/curriculums/5389

2021-01-31 06:41 UTC, sakiytn commented on app/views/items/new.html.erb
> +        <%= f.collection_select(:category_id, Status.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"item-category"}) %>
```
<%= f.collection_select(:category_id, Status.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"item-category"}) %>
```
{include_blank: "---"}入れてるの素晴らしいーーーーー！！！！！！！
Active Hashで { id: 0, name: '---' }を入れない場合はこの記述が必要です！さすが！！！！！

2021-01-31 06:41 UTC, sakiytn commented on spec/factories/items.rb
> +    user_id                  {"1"}
```
    category_id           {"1"}
    status_id             {"1"}
    delivery_fee_id       {"1"}
    shiping_address_id    {"1"}
    shiping_date_id       {"1"}
    price                 {"4000"}
```
Active Hashの値とpriceについては、DB設計でinte型にしていると思うので、ここは""なしの数値として値を入れてあげましょう！（細かくてごめんね）

またuser_idの記述についてですが、テスト環境ではテストデータに紐づくデータを指定することは望ましくないため、下記のようにアソシエーションを組みましょう！
例）
```
association :user 
```

2021-02-01 11:44 UTC, okamin07 commented on app/javascript/item_price.js
> +    addProfitlDom.innerHTML = `${inputValue - tax}`
販売手数料が小数であることになんの違和感も抱かなかったw
計算結果をMath.roundの引数にぶち込んだぜ！

2021-02-01 11:54 UTC, okamin07 commented on app/models/address.rb
> +  belongs_to :prefecture
そっか保存するだけか😦
（なぜこれを書いたか覚えていない笑）

2021-02-01 11:57 UTC, okamin07 commented on app/models/item.rb
> +  has_one_attached :image
DB設計フル無視の謎仕様にしてました！
- has_one:order 
- belongs_to:user に修正！

2021-02-01 13:26 UTC, okamin07 commented on app/models/item.rb
> +  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300,less_than_or_equal_to:9999999},format: {with: /\A[0-9]+\z/}
price についてのバリデーションの「これでいいのか」感がすごい、、、！

2021-02-01 13:58 UTC, okamin07 commented on spec/factories/items.rb
> +    user_id                  {"1"}
`association :user ` で
Itemのインスタンスを生成するのと同時に、関連するUserのインスタンスも生成するのね！
（カリキュラムコピペ侍）

2021-02-01 15:10 UTC, okamin07 commented on app/javascript/item_price.js
> +    addProfitlDom.innerHTML = `${inputValue - tax}`
https://gyazo.com/19d411c3854ad55926404006e2591456

2021-02-01 15:11 UTC, okamin07 commented on spec/factories/items.rb
> +    user_id                  {"1"}
association :user したら「Userがないよ！」って言われ続けて憤怒したけど
userのFactorybotさんがidを生成していないというオチだった

2021-02-04 10:15 UTC, sakiytn commented on app/javascript/item_price.js
> +    addProfitlDom.innerHTML = `${inputValue - tax}`
完璧！最高！

2021-02-04 10:17 UTC, sakiytn commented on app/models/item.rb
> +  has_one_attached :image
正解！天才！

2021-02-04 10:18 UTC, sakiytn commented on spec/factories/items.rb
> +    user_id                  {"1"}
テストおつ！バッチリ！

2021-02-04 10:31 UTC, sakiytn requested changes
大変申し訳ない！
2点だけ修正お願いします。そこさえクリアすればLGTMです！！！！！！！！！

2021-02-04 10:31 UTC, sakiytn commented on app/models/address.rb
> +end
「購入履歴に紐づいた住所」にしたいので、belongs_to :orderの追記をお願いします！！
（指摘漏れしてたかもしれない⋯ごめんなさい😭）

2021-02-04 10:31 UTC, sakiytn commented on app/models/category.rb
> +  end
こちらも指摘漏れですごめんなさい⋯（切腹）
最新のカリキュラムだと、Active Hashにアソシエーションを組むように案内されているのでそれに倣って追記をしましょう。いや、して頂けますでしょうか！😭

ちなみにFurimaの場合だとこのようなアソシエーションになります。↓
```
  include ActiveHash::Associations
  has_many :items
```
Category, Status, ShipingDate, DeliveryFee, ShipingAddressに全て追記でお願いします🙏

参考カリキュラム：
_最終課題補足カリキュラム 〜カテゴリーの選択を工夫しよう〜_
https://master.tech-camp.in/curriculums/4999

2021-02-04 10:31 UTC, sakiytn commented on spec/factories/user.rb
> +    id                    {1}
お？idの指定必要だった⋯！？
ちょっとここは謎なんだけど、ひとまずテストは通ってるからよしとするか⋯
（本当h）

2021-02-04 10:31 UTC, sakiytn commented on spec/factories/user.rb
> +    id                    {1}
お？id必要だった⋯！？
ここは本当は不要なはずなんだけど、ひとまずテストが通ってるもんなぁ⋯
ちょっと謎があるんだけど、とりあえずOKとします！（今度会った時にちょっと見せてほしい）

2021-02-06 12:28 UTC, okamin07 commented on app/models/address.rb
> +end
いえいえ！
DB設計の時点でアソシエーションまで考えてるから
記述してないほうがおかしい！笑

2021-02-06 12:40 UTC, okamin07 commented on app/models/category.rb
> +  end
item.rbには`extend ActiveHash::Associations::ActiveRecordExtensions` 
書いてるのに、我ながら不思議なことをしたもんだ！🌝

2021-02-07 05:21 UTC, sakiytn reviewed
Looks Good To Meです！
お疲れさまでした！！

2021-02-07 10:11 UTC, merged