商品一覧表示
okamin07/furima-877877 pull request #6
Opened 2021-02-08 23:25 UTC by okamin07

# WHY
何か明確に「〇〇を購入したい」と考えているわけではないユーザーに対し、
現在出品されている商品を一覧表示することで購買意欲を掻き立てるため。

# WHAT
- 現在出品されている商品を「出品日時」の降順で表示
- 購入された商品は「Sold Out」の表示
 https://gyazo.com/f13c371b733bf1bf527ebd6ae8d0fc5f
- 何も出品されていないときはダミー商品を表示
https://gyazo.com/93af4797947a8f1780a0cfcc6267e3a6

2021-02-10 03:13 UTC, sakiytn requested changes
レビューミスがありました。ごめんなさい😭一点だけ修正をお願いします！
他は完璧なので実質一発LGTMです！申し訳ございませんでしたァァァ

2021-02-10 03:13 UTC, sakiytn commented on app/models/order.rb
> +  has_one:item
# まじでごめんなさい
おかみん⋯本当に申し訳ない⋯
DB設計の通りにアソシエーションを組んでくれていると思うんだけど、こちらの指摘ミスがあったので一点修正をお願いしたいです。ごめんなさい、ごめんなさい！（土下座）
```
has_one:item 
```
こちらのアソシエーションについて、Itemモデルでは「has_one :order」を組んでいるため、has_oneされるOrderモデルのアソシエーションは「belongs_to :item」になります。

本当にごめんなさい、修正をお願いします！！！
（念のためREADMEも合わせて修正しておくと混乱せずに済むと思います。二度手間で申し訳ない⋯）

2021-02-10 03:13 UTC, sakiytn commented on app/views/items/index.html.erb
> +                    <span>Sold Out!!</span>
# Sold Outの帯は後からの実装でOKだよ
（補足）
sold outの条件分岐については、**受講生さんには基本的に購入機能の実装が完了してから着手してもらうようにご案内しています**！
※これから実装してもらう商品詳細機能でのsold outや「購入画面に進む」ボタンの表示関連も同様

今回は既にOrderモデルを生成してくれているので、一旦そのまま進めましょう！

2021-02-11 02:29 UTC, okamin07 commented on app/models/order.rb
> +  has_one:item
これは俺も気づけよ案件！！！

2021-02-11 02:31 UTC, okamin07 commented on app/views/items/index.html.erb
> +                    <span>Sold Out!!</span>
そうかな、とは思った笑（あのトレロの指示わかりにくいよね）
やんちゃなので手動で購入情報突っ込みました！

2021-02-11 03:28 UTC, sakiytn reviewed
LGTMです！
次に進みましょう〜！

2021-02-12 10:00 UTC, merged